### ISSUE TITLE
Morning Session Discussion

### ISSUE THREAD

**Issue by tarikbouari** [shyusu4/Portfolio#11]
Hi @shyusu4,

 Thank you for your good work, there are a few elements you need to improve in our code

- I kindly suggest you should put some hover effect on your icons.
- I would like to suggest the hover effect on the images and nave bar
- It would be better if you use a descriptive name for the html class
-  kindly add a background to your navbar for a better user experience.
-  I think If you make your contact form responsive it will make your web look better.

**Comment by shyusu4** [comment]
Hi, thank you for your feedback. I like your suggestions and will try to implement them in my code.
